[package]
name = "kernel"
version = "0.1.0"
authors = ["Goran Peretin <goran.peretin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []

[dependencies]
